SRCS = $(wildcard *.java)
CLS  = $(SRCS:.java=.class)

compile:
	javac -classpath . $(SRCS)
run:
	java assignmentP2 "/import/linux/home/vkulkar2/IR/Final Project/vkulkar2_java_part3/docs"
clean:
	rm -f *.class *.csv *.txt